name: Electron

on:
  push:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Package.json info
        uses: rexdefuror/read-package-json@v1.0.5
      - uses: ncipollo/release-action@v1
        with:
          tag: 'v${{ env.PACKAGE_VERSION}}'
          allowUpdates: true
          prerelease: false
          draft: true

  make:
    needs: release
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
        # - name: Package.json info
        #   uses: rexdefuror/read-package-json@v1.0.5
        # - uses: ncipollo/release-action@v1
        #   with:
        #     tag: 'v${{ env.PACKAGE_VERSION}}'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run svelte:build
        #    - run: npm run electron:make
      - run: npm run electron:publish
        #    - run: npm run build --if-present
        #    - run: npm test


